name: PackZip
on:
  push:
    paths:
      - "odex.json"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 1. 准备文件
        run: |
          cp -f $GITHUB_WORKSPACE/odex.sh $GITHUB_WORKSPACE/odex_script_update_online/common
          cp -f $GITHUB_WORKSPACE/odex.json $GITHUB_WORKSPACE/odex_script_update_online/common
          cp -f $GITHUB_WORKSPACE/odex.md $GITHUB_WORKSPACE/odex_script_update_online/common
          sed -i '1d;4d;5d;6d' $GITHUB_WORKSPACE/odex_script_update_online/common/odex.json
          cd $GITHUB_WORKSPACE/odex_script_update_online
          zip -q -r odex_script_update_online.zip *
          mv $GITHUB_WORKSPACE/odex_script_update_online/odex_script_update_online.zip $GITHUB_WORKSPACE/odex_script_update_online.zip
      - name: 2. 读取当前版本和更新日志
        run: |
          echo "GITHUB_version=$(cat $GITHUB_WORKSPACE/odex.json | sed 's/,/\n/g' | grep "version" | sed 's/:/\n/g' | sed '1d;3d;4d' | sed 's/^[ ]*//g')" >> $GITHUB_ENV
          echo "GITHUB_description=$(cat $GITHUB_WORKSPACE/odex.md | sed '1d')" >> $GITHUB_ENV
      - name: 3. 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_version }}
          release_name: MIUI ODEX ${{ env.GITHUB_version }}
          body: ${{ env.GITHUB_description }}
          draft: false
          prerelease: false
      - name: 4. 上传GitHub Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./odex_script_update_online.zip
          asset_name: odex_script_update_online.zip
          asset_content_type: application/zip
      - name: 5. 推送到Magisk Module仓库
        env:
          browser_download_url: ${{ steps.upload-release-asset.outputs.browser_download_url }}
        run: |
          sed -i "s#browser_download_url#http://ghproxy.com/$browser_download_url#g" $GITHUB_WORKSPACE/odex.json