name: release
on:
  push:
    paths:
      - "odex.json"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: 1. 准备文件
        run: |
          echo "version=$(jq -r .version $GITHUB_WORKSPACE/odex.json)" >> $GITHUB_ENV
          echo "versionCode=$(jq -r .versionCode $GITHUB_WORKSPACE/odex.json)" >> $GITHUB_ENV
          echo "ModuleFolderName=odex_script_update_online" >> $GITHUB_ENV
      - name: 2. 制作模块
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          echo "version=${{ env.version }}" >>$GITHUB_WORKSPACE/${{ env.ModuleFolderName }}/module.prop
          echo "versionCode=${{ env.versionCode }}" >>$GITHUB_WORKSPACE/${{ env.ModuleFolderName }}/module.prop
          cd $GITHUB_WORKSPACE/${{ env.ModuleFolderName }}
          zip -q -r ${{ env.ModuleFolderName }}.zip *
          mv $GITHUB_WORKSPACE/${{ env.ModuleFolderName }}/${{ env.ModuleFolderName }}.zip "$GITHUB_WORKSPACE"/GithubRelease/${{ env.ModuleFolderName }}.zip
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo "${{ env.ModuleFolderName }}.zip" > file.log
      - name: 3.上传到Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "MIUI ODEX ${{ env.version }}"
          tag: "${{ env.version }}"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          makeLatest: true
      - name: 4. 再次初始化仓库
        run: |
          rm -rf $GITHUB_WORKSPACE/*
      - uses: actions/checkout@main
      - name: 5. 更新下载链接
        run: |
          git config --global user.email "42595464+DavidPisces@users.noreply.github.com"
          git config --global user.name "泠洛 & 柚稚的孩纸"
          sed -i '4d' $GITHUB_WORKSPACE/odex.json
          browser_download_url=$(curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ github.token }}"   -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/DavidPisces/MIUI-Auto-Odex/releases/tags/${{ env.version }} | jq -r .assets[].browser_download_url | cut -d'"' -f2)
          sed -i '3a "zipUrl": "https://ghproxy.com/'"$browser_download_url"'",' $GITHUB_WORKSPACE/odex.json
          jq . $GITHUB_WORKSPACE/odex.json > $GITHUB_WORKSPACE/new.json
          rm -rf $GITHUB_WORKSPACE/odex.json && mv $GITHUB_WORKSPACE/new.json $GITHUB_WORKSPACE/odex.json
          git add ./odex.json
          if git commit -m "v${{ env.version }}"; then
              echo "push=true" >> $GITHUB_ENV
          else
              echo "push=false" >> $GITHUB_ENV
          fi
      - if: ${{ env.push == 'true' }}
        name: 6. 推送到Magisk Module仓库
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
